// app/javascript/StageSelectHeader.vue
<template>
  <header>
    <img src="../assets/images/logo_transparent.png" alt="サイトロゴ">
    <h1>ゲームと<br>ゴロ合わせで<br>円周率を覚えよう！</h1>
  </header>
</template>

<script>
export default {
}
</script>

<style scoped>
  header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 280px;
    margin-top: 20px;
  }
  img {
    max-height: 100px;
  }
  h1 {
    font-size: 20px;
    color: #ffffff;
  }
</style>

// src/components/StageSelectHeader.tsx
import Image from 'next/image';

function StageSelectHeader() {
  return (
    <header className="flex justify-between items-center w-72 mt-5">
      <Image
        src="/logo_transparent.png"
        alt="site logo"
        width={100}
        height={100}
      />
      <h1 className="text-xl text-white">
        ゲームと
        <br />
        ゴロ合わせで
        <br />
        円周率を覚えよう！
      </h1>
    </header>
  );
}

export default StageSelectHeader;
